name: Maven Package

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        server-id: updater
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    
    - name: Build Plugin
      run: mvn -B package --file pom.xml
      
    - name: Publish to Felipe Repository
      run: mvn --batch-mode deploy
      env:
          MAVEN_USERNAME: ${{ secrets.REPO_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.REPO_TOKEN }}
